apiVersion: v1
kind: Pod
metadata:
  name: hungry-app
  namespace: arena
spec:
  containers:
  - name: app
    image: nginx:latest
    resources:
      requests:
        memory: "999Gi"
        cpu: "999"
